name: PublishNuget

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
    - name: Push
      env:
        ApiKey: ${{ secrets.NUGETAPIKEY }}
        SourceUrl: "https://api.nuget.org/v3/index.json"
      run: dotnet nuget push NOptional.1.0.0.nupkg "$GITHUB_WORKSPACE"/bin/Release --api-key "$ApiKey" --source "$SourceUrl" 
